# Generated by Django 3.2.13 on 2022-07-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_statement',
            field=models.TextField(),
        ),
    ]
