# Generated by Django 3.2.13 on 2022-07-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_alter_problem_problem_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='submission',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='verdict',
            field=models.CharField(choices=[('0', 'Unattempted'), ('1', 'Correct Answer'), ('2', 'WA'), ('3', 'TLE'), ('4', 'CTE'), ('5', 'RTE')], max_length=40),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='test_input',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='test_output',
            field=models.TextField(),
        ),
    ]
