# Generated by Django 3.2.13 on 2022-07-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_auto_20220703_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='language',
            field=models.CharField(choices=[('C', 'C'), ('C++', 'C++'), ('Python3', 'Python3'), ('Java', 'Java')], default='CPP', max_length=20),
        ),
    ]
