# Generated by Django 3.2.13 on 2022-07-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_submissions_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='language',
            field=models.CharField(choices=[('C', 'C'), ('C++', 'C++'), ('Python3', 'Python3'), ('Java', 'Java')], default='C++', max_length=20),
        ),
    ]
