# Generated by Django 3.2.13 on 2022-07-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_alter_submissions_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='verdict',
            field=models.CharField(choices=[('0', 'Unattempted'), ('1', 'Accepted'), ('2', 'WA'), ('3', 'TLE'), ('4', 'CTE'), ('5', 'RTE')], max_length=40),
        ),
    ]
