# Generated by Django 3.2.13 on 2022-07-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_alter_submissions_verdict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissions',
            old_name='submission',
            new_name='submitted_code',
        ),
    ]
