# Generated by Django 3.2.13 on 2022-07-07 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0007_rename_submission_submissions_submitted_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_constraints',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_input',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_output',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
