# Generated by Django 3.2.13 on 2022-07-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0008_auto_20220707_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='problem_constraints',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='problem_input',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='problem_output',
        ),
    ]
