# Generated by Django 3.2.13 on 2022-07-07 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0009_auto_20220707_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='input_output_constraint',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
