# Generated by Django 3.2.13 on 2022-07-12 18:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import judge.models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0010_problem_input_output_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(max_length=100)),
                ('submission_time', models.DateTimeField()),
                ('submitted_code', models.FileField(upload_to=judge.models.Submission.get_upload_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='input_output_constraint',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='problem_title',
        ),
        migrations.RemoveField(
            model_name='testcases',
            name='test_input',
        ),
        migrations.RemoveField(
            model_name='testcases',
            name='test_output',
        ),
        migrations.AddField(
            model_name='problem',
            name='code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcases',
            name='input',
            field=models.FileField(default=django.utils.timezone.now, upload_to=judge.models.Testcases.get_upload_path_input),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcases',
            name='output',
            field=models.FileField(default=django.utils.timezone.now, upload_to=judge.models.Testcases.get_upload_path_output),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Submissions',
        ),
        migrations.AddField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problem'),
        ),
    ]
